FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY client/package.json client/package-lock.json ./
RUN npm install

COPY client/ ./
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
